#!/bin/sh

in=$1;

#strip extension
basename=`echo $in | sed 's/\(.*\)\..*/\1/g'`

#change extension
out=$basename.ptx

#replace special characters with underscores, supress multiple underscores
varname=`echo $basename.ptx | sed -e 's/^[^a-z]*//' -e 's/[^a-z0-9_]/_/g' -e 's/__*/_/g'`

nvcc -ptx $in -o $out

cat $out | sed -e 's/"/\\"/g' -e 's/^.*$/"&\\n"/' | sed -e "1i static const char* $varname = " -e '$a ;' > ${basename}_ptx.h

