#!/bin/csh -f

@ num_args = ${#argv}

if ("${num_args}" != 1) then
    echo "Script assert_non_null_arg needs exactly on non-null argument."
    exit 1 
endif 

set first_arg = `echo "$1" | sed 's/ *//'` 

if ("$first_arg" == "") then
    echo "Script assert_non_null_arg needs exactly on non-null argument."
    exit 1 
endif 

