#!/bin/csh -f

echo cleaning: $1
#
# This one should be first
#
set done = 0
while (! $done)
    ${MAKE_BIN_DIR}include_def SKIP_FOR_EXPORT < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

cat $1 | sed "/UNTESTED_CODE( *) *;/d" | sed "/KJB(UNTESTED_CODE( *) *) *;/d" > temp
/bin/mv temp $1

cat $1 | sed "/SUSPECT_CODE( *) *;/d" | sed "/KJB(SUSPECT_CODE( *) *) *;/d"  > temp
/bin/mv temp $1

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def_head PROGRAMMER_IS_ < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def_head HOW_IT_WAS < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def_head REGRESS_ < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def DEF_OUT < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def FIGURE_IT_OUT < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def_head DUMP_ < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def LOOKS_BUGGY < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def_head XXX < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def NOT_USED < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def NOT_CURRENTLY_USED < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def REINSTATE_SOMETIME < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def NOT_NEEDED < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def OBSOLETE < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def REALLY_TEST < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def TRY_WITHOUT < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

#####################################################################

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def HAVE_NUMERICAL_RECIPES < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def TEST_INTERSECTION_ROUTINES < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def HAVE_VIDEO < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def HAVE_MATLAB < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def HAVE_LOQO < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def DO_BIMODAL_ANALYSIS < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def HAVE_XY < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

#####################################################################

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def TEST_GET_CLUSTER_MEMBERSHIP < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}skip_def TEST_EMULATED_PINAR_CLUSTER_DOC_ORDER < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

#####################################################################


set doing_gamut = `echo $1 | grep gamut/`

# echo doing_gamut: ${doing_gamut}

if ("${doing_gamut}" != "") then
    set done = 0
    while (! $done)
        ${MAKE_BIN_DIR}skip_def HAVE_VARYING_ILLUM < $1 > temp 
        if ($status == 0) set done = 1
        /bin/mv temp $1
    end

    set done = 0
    while (! $done)
        ${MAKE_BIN_DIR}skip_def DO_GEOM_VIEW < $1 > temp 
        if ($status == 0) set done = 1
        /bin/mv temp $1
    end

    set done = 0
    while (! $done)
        ${MAKE_BIN_DIR}skip_def DO_DB_RETINEX < $1 > temp 
        if ($status == 0) set done = 1
        /bin/mv temp $1
    end

    set done = 0
    while (! $done)
        ${MAKE_BIN_DIR}skip_def DO_CLUSTER_GREY_WORLD < $1 > temp 
        if ($status == 0) set done = 1
        /bin/mv temp $1
    end

    set done = 0
    while (! $done)
        ${MAKE_BIN_DIR}skip_def DO_LARGE_VOL_GAMUT_SOLUTION_SELECTION < $1 > temp 
        if ($status == 0) set done = 1
        /bin/mv temp $1
    end

    set done = 0
    while (! $done)
        ${MAKE_BIN_DIR}skip_def DO_RMS_GREY_WORLD < $1 > temp 
        if ($status == 0) set done = 1
        /bin/mv temp $1
    end

    set done = 0
    while (! $done)
        ${MAKE_BIN_DIR}skip_def HAVE_NEURAL_NET < $1 > temp 
        if ($status == 0) set done = 1
        /bin/mv temp $1
    end

    set done = 0
    while (! $done)
        ${MAKE_BIN_DIR}skip_def HAVE_DEP_CORRELATION < $1 > temp 
        if ($status == 0) set done = 1
        /bin/mv temp $1
    end

    set done = 0
    while (! $done)
        ${MAKE_BIN_DIR}skip_def HAVE_CORRELATION_3D < $1 > temp 
        if ($status == 0) set done = 1
        /bin/mv temp $1
    end

    set done = 0
    while (! $done)
        ${MAKE_BIN_DIR}skip_def HAVE_EARTHMOVER < $1 > temp 
        if ($status == 0) set done = 1
        /bin/mv temp $1
    end

    set done = 0
    while (! $done)
        ${MAKE_BIN_DIR}skip_def HAVE_MALONEY_WANDELL < $1 > temp 
        if ($status == 0) set done = 1
        /bin/mv temp $1
    end

    set done = 0
    while (! $done)
        ${MAKE_BIN_DIR}skip_def SUPPORT_DO < $1 > temp 
        if ($status == 0) set done = 1
        /bin/mv temp $1
    end

    set done = 0
    while (! $done)
        ${MAKE_BIN_DIR}skip_def SUPPORT_GAMUT_WITH_SIMPLEX < $1 > temp 
        if ($status == 0) set done = 1
        /bin/mv temp $1
    end

    set done = 0
    while (! $done)
        ${MAKE_BIN_DIR}skip_def SUPPORT_CORR_WITH_GAUSSIAN < $1 > temp 
        if ($status == 0) set done = 1
        /bin/mv temp $1
    end

    set done = 0
    while (! $done)
        ${MAKE_BIN_DIR}skip_def SUPPORT_CORR_WITH_UNIFORM_INV_DIST < $1 > temp 
        if ($status == 0) set done = 1
        /bin/mv temp $1
    end

    set done = 0
    while (! $done)
        ${MAKE_BIN_DIR}skip_def SUPPORT_CORR_WITH_UNIFORM_FITTED < $1 > temp 
        if ($status == 0) set done = 1
        /bin/mv temp $1
    end

    # USE_APRIL_04_CODE_FOR_01 does not seem to be in the code any longer
    # 
    # set done = 0
    # while (! $done)
    #     ${MAKE_BIN_DIR}skip_def USE_APRIL_04_CODE_FOR_01 < $1 > temp 
    #     if ($status == 0) set done = 1
    #     /bin/mv temp $1
    # end
endif 

#######################################################################

set done = 0
while (! $done)
    ${MAKE_BIN_DIR}remove_double_jagged < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
end

set done = 0
set count = 0 
while (! $done)
    ${MAKE_BIN_DIR}remove_empty_def < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
    @ count++

    if (${count} > 20) then
        ${P_STDERR} "Infinite loop suspected in clean_src"
        exit 1
    endif 
end


set done = 0
set count = 0 
while (! $done)
    ${MAKE_BIN_DIR}remove_double_blank < $1 > temp 
    if ($status == 0) set done = 1
    /bin/mv temp $1
    @ count++

    if (${count} > 20) then
        ${P_STDERR} "Infinite loop suspected in clean_src"
        exit 1
    endif 
end


