#!/bin/csh -f 

set found = 0
set src_dir = ""

pushd `pwd` > /dev/null

while ("`pwd`" != "/")
    if (-e Make/init_machine) then
        set found = 1
        break
    endif 

    set src_dir = "../${src_dir}"

    cd ..
end

popd > /dev/null

if (${found}) then
    if ("${src_dir}" == "") then
        set src_dir = "./"
    endif 
else
    set src_dir = "${HOME}/src/"

   if (! -e ${src_dir}Make/init_machine) then
       # We cannot use P_STDERR here because we might not have defined it yet.
       bash -c "echo 1>&2"
       bash -c "echo This directory does not seem to be below a src dirctory with KJB installed. 1>&2"
       bash -c "echo Nor does ${src_dir}Make/init_machine exist.  1>&2"
       bash -c "echo 1>&2"

       exit 1 
   endif 
endif 

source ${src_dir}/Make/init_machine >& /dev/null

echo ${MACHINE}



