#!/bin/csh -f

@ num_args = ${#argv}

if ("${num_args}" != 1) then
    ${P_STDERR} "Script is_link takes exactly one argument."
    exit 1 
endif 

#
# Remove traling slashes.
#
set test_item = `echo ${1} | sed 's#/*$##'`

# Older versions of csh may not have '-'.
#
if ($?tcsh) then
    if (-l ${test_item}) then
        echo 1 
    else 
        echo 0
    endif 
else
    test -L ${test_item}
    if ($status) then
        echo 0
    else
        echo 1 
    endif 
endif 

