#!/bin/csh -f

# This script solves a program in make that you want to update an existing file,
# but the non-existance should not be dealt with using a simple "touch". It is
# not used much currently, but I think it could make some build code more clear,
# so we hang onto it for now. 

set num_args = $#argv

if ("${num_args}" != "1") then
    ${P_STDERR} "Script touch_if_exists should have exactly 2 arguments."
    exit 1
endif 

if (-e "$1") then
    ${KJB_TOUCH} "$1"
endif 

