#!/bin/csh -f 

##############################################################################
#
# Identification:
#     A script to 
#
# Description:
#     This script 
#
# Option arguments: 
#
# |    (The bar stops next line from joining) 
#         Indented
#
# Examples (more to come):
#     blah blah blah
#
# Bugs/deficiencies
#
# Author:
#     Kobus Barnard 
#
##############################################################################

set echo

set source_dir = "$1"
set target_dir = "$2"

pushd "${source_dir}" > /dev/null
    set source_path = `pwd`

    # We set the depth in the next svn command simply because in testing we
    # might have done a shallow checkout. 
    svn up --set-depth=infinity > svn.res

    if (${status}) then
        bash -c 'echo "Svn update failed in `pwd`" 2>&1'
     endif 

    # Save the result for debugging
    cp svn.res svn.res.$$

    set revision = `grep < ${source_dir}/svn.res 'Updated to revision' | set 's/Updated to revision \([0-9]*\).*/\1/'`

    svn log -r ${revision} | grep -v '--------------' > svn.msg

    # Save the result for debugging
    # cp svn.msg svn.msg.$$
popd > /dev/null

rsync -v -a -u --delete --exclude=.svn --exclude-from=/home/ivilab/.my_rsync_excludes "${source_dir}/" "${target_dir}" 

grep < ${source_dir}/svn.res '^[AD]' | sed "s#^A  *\(.*\)#svn add --parents \1#" | sed "s#^D  *\(.*\)#svn rm \1#" > ${target_dir}/svn.cmd
# grep < ${source_dir}/svn.res '^[AMD]' | sed "s#^A  *\(.*\)#cp ${source_path}/\1 .; svn add --parents \1#" |  sed "s#^M  *\(.*\)#/bin/cp -rf ${source_path}/\1 .#" | sed "s#^D  *\(.*\)#svn rm \1#" > ${target_dir}/svn.cmd
# cp ${source_dir}/svn.msg  ${target_dir}/svn.msg

pushd "${target_dir}" > /dev/null
    if ($?KJB_VERBOSE) then  
        cat svn.cmd
        echo ""
        echo Revision: ${revision}
        echo ""
        cat  svn.msg
    endif 

    source svn.cmd

    set password = `cat /home/ivilab/.ivilab-sync`
    svn commit --file svn.msg --username ivilab-sync --password ${password} 
popd > /dev/null






