#!/bin/csh -f

# We assume that if the version of "test" does not like the
# input, the status will be greater than one. 


test "$1" -ot "$2" 

set system_test_status = $status

if (${system_test_status} == 0) then
   set older_than = "1"
else if (${system_test_status} == 1) then
   set older_than = "0"
else if (${system_test_status} > 2) then
   set have_stat = 0

   if ("${KJB_STAT_FLAVOR}" == "bsd") then
       eval set `stat -s "$1"`
       set mod_time_1 = ${st_mtime}
       eval set `stat -s "$2"`
       set mod_time_2 = ${st_mtime}
       set have_stat = 1
   else if ("${KJB_STAT_FLAVOR}" == "gnu") then
       set mod_time_1 = `stat -c '%Y' "$1"`
       set mod_time_2 = `stat -c '%Y' "$2"`
       set have_stat = 1
   endif 

   if (${have_stat}) then
       if (${mod_time_1} <= ${mod_time_2}) then
           set older_than = "0"
       else 
           set older_than = "1"
       endif 
   else 
       ${P_STDERR} "Script test_older_than failed."
       exit 1 
   endif 
endif 

echo $older_than
              
