#!/bin/csh -f

# We assume that we have sourced init_compile. 

# Using stderr for unbuffered output. 

${P_STDERR} "--- Process $$ is in test_kjb_lock_2."

if (($?KJB_LOCK_TIME_STAMP) && (-e ${KJB_LOCKFILE_PATH}test_kjb_lock)) then
    set can_skip = `${MAKE_SCRIPT_PATH}test_older_than ${KJB_LOCK_TIME_STAMP} "${KJB_LOCKFILE_PATH}test_kjb_lock"`

    if (${can_skip}) then
        ${P_STDERR} "^^^ Process $$ is skipping touching ${KJB_LOCKFILE_PATH}test_kjb_lock as it is new."
        set x = $$ ; @ x %= 100 ; sleep 0.$x >& /dev/null
        echo $BEEP
        exit 0
    endif 
endif 

${P_STDERR} "@@@ Process $$ is continuing in test_kjb_lock_2."

# The sleeps should hold up the exit of all other processes. 
${P_STDERR} "@@@ Process $$ will add to ${KJB_LOCKFILE_PATH}test_kjb_lock after sleeping"
sleep 2
${P_STDERR} "@@@ Process $$ is adding ${KJB_LOCKFILE_PATH}test_kjb_lock" 
echo $$ >> ${KJB_LOCKFILE_PATH}test_kjb_lock
sleep 2
${P_STDERR} "@@@ Process $$ is done" 



