#!/bin/csh -f

# We assume that we have sourced init_compile. 

# Using stderr for unbuffered output. 

${P_STDERR} "--- Process $$ is in test_kjb_lock_2 (lockfile is ${KJB_LOCKFILE_PATH}."

if (($?KJB_LOCK_TIME_STAMP) && (-e test_kjb_lock,result)) then
    set can_skip = `${MAKE_SCRIPT_PATH}test_older_than ${KJB_LOCK_TIME_STAMP} "test_kjb_lock.result"`

    if (${can_skip}) then
        ${P_STDERR} "^^^ Process $$ is skipping touching test_kjb_lock.result as it is new."
        set x = $$ ; @ x %= 100 ; sleep 0.$x >& /dev/null
        echo $BEEP
        exit 0
    endif 
endif 

${P_STDERR} "@@@ Process $$ is continuing in test_kjb_lock_2."

# The sleeps should hold up the exit of all other processes. 
${P_STDERR} "@@@ Process $$ will add to test_kjb_lock.result after sleeping"
sleep 2
${P_STDERR} "@@@ Process $$ is adding to test_kjb_lock.result" 
echo $$ >> test_kjb_lock.result
sleep 2
${P_STDERR} "@@@ Process $$ is done" 



