#!/bin/csh -f

# We assume that we have sourced init_compile. 

setenv KJB_LOCKING_METHOD "fallback"
setenv KJB_LOCKING_METHOD "flock"
setenv KJB_LOCKING_METHOD "lockfile-progs"

$KJB_RM ${KJB_LOCKFILE_DIR}test_kjb_lock

${MAKE_SCRIPT_PATH}kjb_lock ${MAKE_SCRIPT_PATH}test/test_kjb_lock_2 & 
${MAKE_SCRIPT_PATH}kjb_lock ${MAKE_SCRIPT_PATH}test/test_kjb_lock_2 & 
${MAKE_SCRIPT_PATH}kjb_lock ${MAKE_SCRIPT_PATH}test/test_kjb_lock_2 & 
${MAKE_SCRIPT_PATH}kjb_lock ${MAKE_SCRIPT_PATH}test/test_kjb_lock_2 & 
${MAKE_SCRIPT_PATH}kjb_lock ${MAKE_SCRIPT_PATH}test/test_kjb_lock_2 & 

echo "Script test_kjb_lock is trying a wait."

wait

echo "=============="
${KJB_CAT} ${KJB_LOCKFILE_DIR}test_kjb_lock
echo "=============="


