#!/bin/bash

##############################################################################
#
# Identification:
#     Make thumbnail files of all NED-13 tiles in a local directory.
#
# Description:
#     This makes thumbnail files of all the NED13 data in the DATA directory
#     below.  Output is written to the current directory.  It is inevitably a
#     slow process.  First argument (required) must be the the path+name of
#     DEM-to-image converter.  If you have the program "float2img" (found in
#     this directory) compiled and reachable from your current PATH, then you
#     can invoke this script like so:
# |           ./make_thumbs `which float2img`
#
#     In this subsequent paragraph, the second great thing this script does is
#     detailed.
#
# Option arguments: 
#
# |     EXEPATH
#          Path plus filename of a program to convert DEM tiles to images.
#          It's the same as the third argument to script "build_thumbs" (q.v.).
#
# Author:
#     Andrew Predoehl
#
##############################################################################

# $Id: make_thumbs 14561 2013-06-03 20:13:24Z predoehl $


DATA=/net/v04/data_3/trails/elevation/ned_13as/llgrid
pushd `dirname $1` || exit 1
EXE=`pwd -P`/`basename $1`
popd || exit 1
test -d thumb_abs || mkdir thumb_abs || exit 1
( cd thumb_abs && ../build_thumbs --absolute $DATA $EXE ) || exit 1
test -d thumb_rel || mkdir thumb_rel || exit 1
( cd thumb_rel && ../build_thumbs --relative $DATA $EXE ) || exit 1

