#!/bin/sh
# This script is meant to be run in the parent of subdirectory llgrid.
# It uses ImageMagick to make a montage of all the NED13 tiles.
# $Id: make_montage 14509 2013-05-24 01:10:11Z predoehl $
mkdir /tmp/montage || exit 1
chmod 700 /tmp/montage || exit 1
for X in /net/v04/data_3/trails/elevation/ned_13as/llgrid/*.zip
do  Y=`basename $X`
    T=${Y%.zip} # tile name
    N="$N ${T%w???}" # north (latitude) part
    W="$W ${T#n??}" # west (longitude) part
done
N=`echo "$N" | sed -e "s/ /\\n/g" | sort | uniq`
W=`echo "$W" | sed -e "s/ /\\n/g" | sort | uniq`
SIZE="200x200"
EMPTY=/tmp/montage/empty.png
SOURCE=thumb_abs # source directory, thumb_rel or thumb_abs
test -r $EMPTY || convert xc:none -size $SIZE $EMPTY || exit 1
LON=0
for X in $W
do  LAN=0
    for Y in $N
    do T=$Y$X
        REAL=$SOURCE/$T.jpeg
        if [ -r $REAL ]
        then    convert $REAL -flip -flop -resize $SIZE /tmp/montage/$T.png \
                    || exit 1
        else    ln $EMPTY /tmp/montage/$T.png || exit 1
        fi
        LAN=`expr 1 + $LAN`
    done
    LON=`expr 1 + $LON`
done
FINAL=montage.jpeg
montage /tmp/montage/n*.png -geometry $SIZE -tile ${LON}x$LAN $FINAL || exit 1
mogrify -flip -flop $FINAL || exit 1
rm -rf /tmp/montage
