#!/bin/bash -ex
# $Id: varying_spq 20310 2016-02-01 11:32:25Z predoehl $

#for eee in 101 102 103 105 108 110 115
#EXTRA_CXX_FLAGS = -DSPQ_EXP=$eee -DSPQ_ROOT=100

for eee in -2 -3 -10 -20 -30 -40 -50
do sed -i -e '/^EXTRA_CXX_FLAGS/d' -e "1i\
EXTRA_CXX_FLAGS = -DSPQ_EXP=$eee
" Makefile-2
   touch test_spq.cpp
   env PRODUCTION=1 make
#  make a 20-trajectory one for visualization
   fnd=det_$eee.svg
   fns=sto_$eee.svg
   ./test_spq -w2 -i20 $fnd $fns
#  make a big one: many samples.  poor visualization but better histogram quality
#  big one lacks .svg filename suffix, instead has .xxx suffix.
   fndx=${fnd%.svg}.xxx
   fnsx=${fns%.svg}.xxx
   ./test_spq -w2 -i1000 $fndx $fnsx
   for fff in $fndx $fnsx
   do for ((n=0; n < 11; ++n))
      do sed -n "/sink_${n}_distance_/s/.*distance_\(.*\).>/\1/p" <$fff >dist_${fff%.xxx}_sink_$n.txt
	  done
   done
done
sed -i -e '/^EXTRA_CXX_FLAGS/d' Makefile-2
# Generate histogram plots, to see empirical distribution of path lengths.
./spq_histo.bash
