#!/bin/tcsh -f

if ("$#argv" != 2) then
   echo "Script strip_ex7_files needs exactly two parameters."
   exit 1
endif 

if (! -e "$1") then
   echo "First argument to script strip_ex7_files does not exist."
   exit 1
else if (-e $2) then
    chmod u+w $2
endif 

cat $1 | sed '/^:* *$/d' | sed '/^:*\"/d' | sed 's///g' > $2
chmod u-w $2

