/*
 * $Id: int_vec_minmax.c 21491 2017-07-20 13:19:02Z kobus $
 */

#include "l/l_incl.h"
#include <stdio.h>
#include <stdlib.h>


static void we_expect( int boolean )
{
    if ( ! boolean )
    {
        puts( "Fail!" );
        exit( EXIT_BUG );
    }
}


int main(void)
{
    int         i, j, n;
    int         SIZE = 101;
    Int_vector  *v1 = 0;

    /* Contents of the following array was randomly generated by
        perl -e 'for $i (0..100) { printf "%d,\n", 20000*rand()-10000; }' 
     */
    const double nonsense[] =
    {
         8065,
        -1537,
        -8860,
        -1130,
        -6836,
        -9346,
        -3035,
        -4108,
         3162,
          146,
         8556,
         2207,
        -5333,
        -7756,
         6900,
        -3704,
         8646,
        -9346,
          508,
        -6588,
        -5332,
        -5625,
         3029,
        -2123,
         8460,
        -3589,
        -3997,
        -3064,
         9270,  /* nonsense[28] is maximum */
        -9886,  /* nonsense[29] is minimum */
         3021,
         4934,
         6122,
         4962,
        -8268,
        -7832,
         7405,
        - 847,
         5435,
         6432,
         7240,
         4362,
        -4735,
        -5414,
        -2632,
         1618,
        - 306,
         6228,
         4066,
         4673,
         2441,
          253,
        -3429,
         7661,
        -1667,
         7957,
         3822,
          953,
         4551,
        -7447,
         9157,
        -2450,
          759,
        -4523,
         2911,
        -8269,
        -6036,
         4265,
        -1896,
        -7959,
        -5117,
         6862,
        -2315,
         7356,
         3038,
        -6977,
        -1463,
        -6602,
         3212,
        -2380,
        - 920,
         8565,
        -9496,
         3550,
        -2780,
        -6252,
         3448,
         7035,
         3245,
         7134,
         1884,
        -3642,
        - 493,
        - 690,
           33,
          589,
         3167,
        -2218,
        -3836,
        - 853,
        - 475
    };

    get_target_int_vector( &v1, SIZE );
 
    for( i = 0; i < SIZE; ++i )
    {
        v1 -> elements[ i ] = nonsense[ i ];
    }

    j = get_max_int_vector_element( v1, &n );

    we_expect( 28 == j );
    we_expect( 9270 == n );

    n = 0;
    j = get_min_int_vector_element( v1, &n );

    we_expect( 29 == j );
    we_expect( -9886 == n );

    n = max_int_vector_element( v1 );

    we_expect( 9270 == n );

    n = min_int_vector_element( v1 );

    we_expect( -9886 == n );

    free_int_vector( v1 );
    
    return EXIT_SUCCESS;
}

